### PR TITLE
New question + punctuation

### PR DESCRIPTION
**Pull request by ThatOneCalculator**

### CODE REVIEW

**Comment by Jimmysit0** [comment]
Thank you for your pull request! But every question must have 4 possible answers, could you add an extra possible answer? Then I'll merge

**Comment by ThatOneCalculator** [comment]
@Jimmysit0 done lol

**Comment by Jimmysit0** [comment]
Sorry for the delayed response, I'll be testing this now

**Comment by Jimmysit0** [comment]
image

Thanks for your pr

**Pull request merged**
